// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'search_history_entity.dart';
import 'ticker_entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 477273669783013897),
    name: 'TickerEntity',
    lastPropertyId: const obx_int.IdUid(12, 4408383742068396147),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 2814459175052402350),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 4273298668090867394),
        name: 'symbol',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(1, 8016379858016245136),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 4490096888114673431),
        name: 'lastPrice',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 2360670576321116238),
        name: 'openPrice',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2742340243880327812),
        name: 'highPrice',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 3689802043353928527),
        name: 'lowPrice',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 2148038553409372969),
        name: 'bidPrice',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(8, 1423510202094038862),
        name: 'askPrice',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(9, 4619369482897846678),
        name: 'priceChange',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(10, 3027773527055018836),
        name: 'priceChangePercent',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(11, 2260044863163660443),
        name: 'volume',
        type: 8,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(12, 4408383742068396147),
        name: 'quoteVolume',
        type: 8,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 7413174995064086404),
    name: 'SearchHistoryEntity',
    lastPropertyId: const obx_int.IdUid(3, 7988309309959483057),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4511157630848874137),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5391002006663341144),
        name: 'symbol',
        type: 9,
        flags: 34848,
        indexId: const obx_int.IdUid(2, 356448650320046573),
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 7988309309959483057),
        name: 'searchedAt',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(2, 7413174995064086404),
    lastIndexId: const obx_int.IdUid(2, 356448650320046573),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    TickerEntity: obx_int.EntityDefinition<TickerEntity>(
      model: _entities[0],
      toOneRelations: (TickerEntity object) => [],
      toManyRelations: (TickerEntity object) => {},
      getId: (TickerEntity object) => object.id,
      setId: (TickerEntity object, int id) {
        object.id = id;
      },
      objectToFB: (TickerEntity object, fb.Builder fbb) {
        final symbolOffset = fbb.writeString(object.symbol);
        fbb.startTable(13);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, symbolOffset);
        fbb.addFloat64(2, object.lastPrice);
        fbb.addFloat64(3, object.openPrice);
        fbb.addFloat64(4, object.highPrice);
        fbb.addFloat64(5, object.lowPrice);
        fbb.addFloat64(6, object.bidPrice);
        fbb.addFloat64(7, object.askPrice);
        fbb.addFloat64(8, object.priceChange);
        fbb.addFloat64(9, object.priceChangePercent);
        fbb.addFloat64(10, object.volume);
        fbb.addFloat64(11, object.quoteVolume);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final symbolParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final lastPriceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final openPriceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          10,
          0,
        );
        final highPriceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          12,
          0,
        );
        final lowPriceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          14,
          0,
        );
        final bidPriceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          16,
          0,
        );
        final askPriceParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          18,
          0,
        );
        final priceChangeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          20,
          0,
        );
        final priceChangePercentParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          22,
          0,
        );
        final volumeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          24,
          0,
        );
        final quoteVolumeParam = const fb.Float64Reader().vTableGet(
          buffer,
          rootOffset,
          26,
          0,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final object = TickerEntity(
          symbol: symbolParam,
          lastPrice: lastPriceParam,
          openPrice: openPriceParam,
          highPrice: highPriceParam,
          lowPrice: lowPriceParam,
          bidPrice: bidPriceParam,
          askPrice: askPriceParam,
          priceChange: priceChangeParam,
          priceChangePercent: priceChangePercentParam,
          volume: volumeParam,
          quoteVolume: quoteVolumeParam,
          id: idParam,
        );

        return object;
      },
    ),
    SearchHistoryEntity: obx_int.EntityDefinition<SearchHistoryEntity>(
      model: _entities[1],
      toOneRelations: (SearchHistoryEntity object) => [],
      toManyRelations: (SearchHistoryEntity object) => {},
      getId: (SearchHistoryEntity object) => object.id,
      setId: (SearchHistoryEntity object, int id) {
        object.id = id;
      },
      objectToFB: (SearchHistoryEntity object, fb.Builder fbb) {
        final symbolOffset = fbb.writeString(object.symbol);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, symbolOffset);
        fbb.addInt64(2, object.searchedAt.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final symbolParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final searchedAtParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final object = SearchHistoryEntity(
          symbol: symbolParam,
          searchedAt: searchedAtParam,
          id: idParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [TickerEntity] entity fields to define ObjectBox queries.
class TickerEntity_ {
  /// See [TickerEntity.id].
  static final id = obx.QueryIntegerProperty<TickerEntity>(
    _entities[0].properties[0],
  );

  /// See [TickerEntity.symbol].
  static final symbol = obx.QueryStringProperty<TickerEntity>(
    _entities[0].properties[1],
  );

  /// See [TickerEntity.lastPrice].
  static final lastPrice = obx.QueryDoubleProperty<TickerEntity>(
    _entities[0].properties[2],
  );

  /// See [TickerEntity.openPrice].
  static final openPrice = obx.QueryDoubleProperty<TickerEntity>(
    _entities[0].properties[3],
  );

  /// See [TickerEntity.highPrice].
  static final highPrice = obx.QueryDoubleProperty<TickerEntity>(
    _entities[0].properties[4],
  );

  /// See [TickerEntity.lowPrice].
  static final lowPrice = obx.QueryDoubleProperty<TickerEntity>(
    _entities[0].properties[5],
  );

  /// See [TickerEntity.bidPrice].
  static final bidPrice = obx.QueryDoubleProperty<TickerEntity>(
    _entities[0].properties[6],
  );

  /// See [TickerEntity.askPrice].
  static final askPrice = obx.QueryDoubleProperty<TickerEntity>(
    _entities[0].properties[7],
  );

  /// See [TickerEntity.priceChange].
  static final priceChange = obx.QueryDoubleProperty<TickerEntity>(
    _entities[0].properties[8],
  );

  /// See [TickerEntity.priceChangePercent].
  static final priceChangePercent = obx.QueryDoubleProperty<TickerEntity>(
    _entities[0].properties[9],
  );

  /// See [TickerEntity.volume].
  static final volume = obx.QueryDoubleProperty<TickerEntity>(
    _entities[0].properties[10],
  );

  /// See [TickerEntity.quoteVolume].
  static final quoteVolume = obx.QueryDoubleProperty<TickerEntity>(
    _entities[0].properties[11],
  );
}

/// [SearchHistoryEntity] entity fields to define ObjectBox queries.
class SearchHistoryEntity_ {
  /// See [SearchHistoryEntity.id].
  static final id = obx.QueryIntegerProperty<SearchHistoryEntity>(
    _entities[1].properties[0],
  );

  /// See [SearchHistoryEntity.symbol].
  static final symbol = obx.QueryStringProperty<SearchHistoryEntity>(
    _entities[1].properties[1],
  );

  /// See [SearchHistoryEntity.searchedAt].
  static final searchedAt = obx.QueryDateProperty<SearchHistoryEntity>(
    _entities[1].properties[2],
  );
}
